### PR TITLE
Added french posts translation for testing internationalization (i18n)

### PR DESCRIPTION
**Pull request by remyj38**

### CODE REVIEW

**Comment by Xzya** [comment]
Any update on this? It would be of great help for testing new themes.

Thanks!

**Comment by jhabdas** [comment]
For sites using i18n having a basic example which adds relevant config seems useful. In #15 there is also an opportunity to add config to enhance the presentation of many sites—but it's opinionated and, as in the case of this pull, the config updates add a level of subjectivity to what the concept of a “basic” theme demo really means.

Having a standardized method for enabling themes to pass Hugo (but not theme) specific configuration options along with themes and have those settings variadically control the build output without dropping in a kitchen sink of params will help highlight themes which are built to function without a special, theme-specific set of params.

**Comment by onedrawingperday** [comment]
@digitalcraftsman 

This oldish Pull Request looks very good and I suggest that you merge it since it would extend the HugoBasicExample for supporting i18, (in this case English and French).

**Comment by digitalcraftsman** [comment]
Having an example to showcase the i18n capabilities is a good extension. However, from a long-term perspective it can happen that some parts of the documentation (no matter of language) is outdated because features changed or have been deprecated.

The English version of this content has been written ages ago but still holds true after browsing some documents. @onedrawingperday would you leave the content as it is or would you rather replace it with some more neutral (meaning time-independent) content?

This are just my 2 cents. However, this translation is a nice addition and most of the content will still hold true for a while.

**Comment by onedrawingperday** [comment]
>The English version of this content has been written ages ago but still holds true after browsing some documents. @onedrawingperday would you leave the content as it is or would you rather replace it with some more neutral (meaning time-independent) content?

I agree with you. The content needs to change in this repo to something more neutral. This will be addressed in a coming PR.

**Pull request merged**
